#config_version=6

mode:
  start_events: start_mode_skull_wave1
  stop_events: stop_mode_skull_wave1
  priority: 200

shot_profiles:
  arrow_shot_profile:
    states:
      - name: lit
        show: on
      - name: unlit
        show: off
  #  loop: true

shots:
  sa1:
    switch: s_left_orbit
    profile: arrow_shot_profile
    show_tokens:
      light: l_left_orbit_arrow
  sa2:
    switch: s_centriguge_enter
    profile: arrow_shot_profile
    show_tokens:
      light: l_centriguge_arrow
  sa3:
    switch: s_ramp
    profile: arrow_shot_profile
    show_tokens:
      light: l_ramp_arrow
  sa4:
    switch: s_microscope_left
    profile: arrow_shot_profile
    show_tokens:
      light: l_microscope_left_arrow
  sa5:
    switch: s_microscope_right
    profile: arrow_shot_profile
    show_tokens:
      light: l_microscope_right_arrow
  sa6:
    switch: s_right_spinner
    profile: arrow_shot_profile
    show_tokens:
      light: l_right_spinner_arrow

shot_groups:
  arrow_shots: 
    shots: sa1, sa2, sa3, sa4, sa5, sa6
    restart_events: mode_skull_wave1_started

variable_player:
  arrow_shots_lit_hit:
    score: 250_000
    
event_player:
  arrow_shots_unlit_complete: stop_mode_skull_wave1

  # less than 2 balls -> END