#config_version=6

# Base mode that starts at the beginning of each ball
# and stops at the end of each ball.

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

event_player:
  mode_base_started:
    - start_mode_bumpers
    - start_mode_csi_lanes
    - start_mode_skull
    - stop_skull_motor
  mode_base_will_stop:
    - stop_mode_bumpers
    - stop_mode_csi_lanes
    - stop_mode_skull
    - stop_skull_motor
#  s_scoop_active:
#    - start_mode_selectmission

slide_player:
  mode_base_started: base_slide

widget_player:
  player_added: player_addded_widget
  timer_player_added_timer_complete:
    player_addded_widget:
      action: remove

timers:
  player_added_timer:
    end_value: 1
    tick_interval: 0.7s
    start_running: true
    control_events:
      - event: player_added
        action: restart