#config_version=6

mode:
  start_events: start_mode_selectmission
  stop_events: stop_mode_selectmission
  priority: 200
  code: mpf.modes.carousel.code.carousel.Carousel

mode_settings:
  selectable_items:
    - skull
    - centrifuge
    - microscope
  next_item_events: s_right_flipper_active
  previous_item_events: s_left_flipper_active

event_player:
  both_flippers_one:
    - stop_mode_selectmission
  
widget_player:
  mode_selectmission_started: selectmission_widget  
