#config_version=6

mode:
  start_events: start_mode_bumpers
  stop_events: stop_mode_bumpers
  priority: 200

shots:
  bumper1:
    switch: s_popbumper1
  bumper2:
    switch: s_popbumper2
  bumper3:
    switch: s_popbumper3

shot_groups:
  bumpers: 
    shots: bumper1, bumper2, bumper3

timers:
  bumper_timer:
    end_value: 1
    tick_interval: 0.5s
    start_running: true
    control_events:
      - event: bumpers_hit
        action: restart

widget_player:
  bumpers_hit: 
    bumper_widget
  timer_bumper_timer_complete:
    bumper_widget:
      action: remove

variable_player:
  bumpers_hit: 
    score: 3_000

sound_player:
  bumpers_hit:
    bumper_sound:
      bus: effects

