#config_version=6

mode:
  start_events: start_mode_bumpers
  stop_events: stop_mode_bumpers
  priority: 200

shots:
  bumper1:
    switch: s_popbumper1
  bumper2:
    switch: s_popbumper2
  bumper3:
    switch: s_popbumper3

shot_groups:
  bumpers: 
    shots: bumper1, bumper2, bumper3

variable_player:
  bumpers_hit: 
    score: 1_000
