#config_version=6

digital_outputs:
  c_motorized_skull:
    number: 1-0-4
    type: driver
# Skull_motor_relay: 1-0-5

# Centrifuge
# Centrifuge_motor: 1-0-3
# Centrifuge motor_relay: 1-0-2

motors:
  skull_motor:
    motor_left_output: c_motorized_skull
    position_switches: !!omap
      - home: s_skull_pos_down
      - pos0: s_skull_pos_down
      - pos1: s_skull_pos_mid
      - pos2: s_skull_pos_up
    reset_position: home
    go_to_position:
      stop_skull_motor: home
      go_position0: pos0
      go_position1: pos1
      go_position2: pos2