#config_version=6

switches:
  s_left_flipper:
    number: 0-0-8
    tags: left_flipper
  s_right_flipper:
    number: 0-0-9
    tags: right_flipper
    
#! Slingshoots
  s_sling_left:
    number: 0-0-10
  s_sling_right:
    number: 0-0-11

  s_start:
    number: 0-0-3
    tags: start

  s_drain:
    number: 1
    
  s_trough1:
    number: 2
  s_trough2:
    number: 3
  s_trough3:
    number: 4
  s_trough4:
    number: 5
#!  s_trough5:
#!    number: 6
#!  s_trough6:
#!    number: 7
#!    type: NC
  s_trough_jam:
    number: 8
    type: NC
    
  s_plunger_lane:
    number: 2-6
  s_launch_button:
    number: 1-5
    
  s_popbumper1:
    number: 0-0-4
  s_popbumper2:
    number: 0-0-5
  s_popbumper3:
    number: 0-0-6

  s_scoop:
    number: 0-0-7    

  s_right_orbit:
    number: 4-0-8

  s_right_inlane:
    number: 5-0-7
    tags: playfield_active
  s_right_outlane:
    number: 5-0-8
    tags: playfield_active
  s_left_inlane1:
    number: 5-0-9
    tags: playfield_active
  s_left_inlane2:
    number: 5-0-10
    tags: playfield_active
  s_left_outlane:
    number: 5-0-11
    tags: playfield_active

  s_ramp:
    number:
  s_skull_lock1:
    number:
  s_skull_lock2:
    number:

  s_morgue:
    number:

  s_left_orbit:
    number:

  s_centriguge_enter:
    number:

  s_microscope_left:
    number:
  s_microscope_right:
    number:

  s_right_spinner:
    number:

  s_bullet1:
    number:
  s_bullet2:
    number:
  s_bullet3:
    number:
  s_bullet4:
    number:
  s_bullet5:
    number:

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4
#!  - s_trough5
#!  - s_trough6
