#config_version=6

switches:

# Flippers
  s_left_flipper:
    number: 0-0-8
    tags: left_flipper
  s_right_flipper:
    number: 0-0-9
    tags: right_flipper
    
#! Slingshoots
  s_sling_left:
    number: 1-0-43
  s_sling_right:
    number: 1-0-51

  s_start:
    number: 1-0-89
    tags: start

# See how it is workong on the mmachine
# as it seems not exist !!!!
#  s_drain:
#    number: 
    
  s_trough1:
    number: 1-0-66
  s_trough2:
    number: 1-0-58
  s_trough3:
    number: 1-0-50
  s_trough4:
    number: 1-0_42
  s_trough_jam:
    number: 1-0-74
    type: NC
  
  s_plunger_lane:
    number: 1-0-82
#  s_launch_button:
#    number: 1-5
    
  s_popbumper1:
    number: 1-0-75
  s_popbumper2:
    number: 1-0-83
  s_popbumper3:
    number: 1-0-91

# Lab Scoop
  s_scoop: 
    number: 1-0-52  

  s_right_orbit:
    number: 1-0-84
    tags: playfield_active

  s_right_inlane:
    number: 1-0-59
    tags: playfield_active
  s_right_outlane:
    number: 1-0-67
    tags: playfield_active
  s_left_inlane1:
    number: 1-0-35
    tags: playfield_active
  s_left_inlane2:
    number: 1-0-54
    tags: playfield_active
  s_left_outlane:
    number: 1-0-90
    tags: playfield_active

  s_ramp:
    number: 1-0-68
    tags: playfield_active
  

  s_morgue:
    number: 1-0-60

  s_left_orbit:
    number: 1-0-73
    tags: playfield_active

  s_centriguge_enter:
    number: 1-0-36
    tags: playfield_active

  s_microscope_left:
    number: 1-0-64
    tags: playfield_active
  s_microscope_right:
    number: 1-0-72
    tags: playfield_active

  s_right_spinner:
    number: 1-0-76
    tags: playfield_active

  s_left_spinner:
    number: 1-0-80
    tags: playfield_active

  # Bullets
  s_bullet1:
    number: 1-0-32
    tags: playfield_active
  s_bullet2:
    number: 1-0-38
    tags: playfield_active
  s_bullet3: 
    number: 1-0-61
    tags: playfield_active
  s_bullet4:
    number: 1-0-69
    tags: playfield_active
  s_bullet5:
    number: 1-0-37
    tags: playfield_active

  # DNA
  s_DNA_D:
    number: 1-0-56
    tags: playfield_active
  s_DNA_N:
    number: 1-0-48
    tags: playfield_active
  s_DNA_A:
    number: 1-0-40
    tags: playfield_active

  # Skull
  s_skull_pos_up:
    number: 1-0-41
  s_skull_pos_mid:
    number: 1-0-49
  s_skull_pos_down:
    number: 1-0-57
  s_skull_lock1:
    number: 1-0-88
  s_skull_lock2:
    number: 1-0-33

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4
