#config_version=6

lights:
# Bottom lanes
# CSI Lanes
  l_lane_c:
    number:
  l_lane_s:
    number:
  l_lane_i:
    number:

  l_scoop_bonus:
    number:  

  l_right_orbit_bonus:
    number:

# Skull
  l_skull_light_lock:
    number:
  l_skull_lock1:
    number:
  l_skull_lock2:
    number:

# Evidences Arrows lights
  l_evdence_arrow_1:
    number:
  l_evdence_arrow_2:
    number:
  l_evdence_arrow_3:
    number:
  l_evdence_arrow_4:
    number:
  l_evdence_arrow_5:
    number:
  l_evdence_arrow_6:
    number:
    
