#config_version=6

coils:
# Flippers
  c_flipper_left_main:
    number: 0-0-8
    default_pulse_ms: settings.flipper_main_coil_power
    allow_enable: true
  c_flipper_right_main:
    number: 0-0-9
    default_pulse_ms: settings.flipper_main_coil_power
    allow_enable: true
  c_flipper_lefttop_main:
    number: 0-0-10
    default_pulse_ms: settings.flipper_main_coil_power
    allow_enable: true

# Slingshoots
  c_sling_left:
    number: 1-0-0
    default_pulse_ms: settings.slingshot_power
  c_sling_right:
    number: 1-0-1
    default_pulse_ms: settings.slingshot_power

# Trough Mecanism
  c_trough_eject:
    number: 0-0-11
    default_pulse_ms: 20
  c_plunger:
    number: 0-0-12
    default_pulse_ms: 20

# !!! Not present on this machine 
# Need to see how Through device is on SAM machines
  c_drain_eject:
    number: 3
    default_pulse_ms: 20

# Pop Bumpers
  c_popbumper1:
    number: 0-0-4
    default_pulse_ms: 23
  c_popbumper2:
    number: 0-0-5
    default_pulse_ms: 23
  c_popbumper3:
    number: 0-0-6
    default_pulse_ms: 23

# Lock Posts
  c_centrifuge_post:
    number: 0-0-7
  c_left_post:
    number: 0-0-2
  c_right_post:
    number: 1-0-6

# Ejects
  c_morgue_eject:
    number: 0-0-15
  s_scoop_eject:
    number: 0-0-1

# 3 Bank Drop Targets
  c_drop_target:
    number: 0-0-3

autofire_coils:
  ac_popbumper1:
    coil: c_popbumper1
    switch: s_popbumper1
  ac_popbumper2:
    coil: c_popbumper2
    switch: s_popbumper2
  ac_popbumper3:
    coil: c_popbumper3
    switch: s_popbumper3
  ac_slingshot_left:
    coil: c_sling_left
    switch: s_sling_left
  ac_slingshot_right:
    coil: c_sling_right
    switch: s_sling_right
    
ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    eject_timeouts: 3s
#    debug: true
  bd_plunger:
    ball_switches: s_plunger_lane
    mechanical_eject: true
    eject_timeouts: 3s

playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right_main
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3
  lefttop_flipper:
    main_coil: c_flipper_lefttop_main
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3

