#config_version=6

config:
  - config_settings.yaml
  - config_hardware.yaml
  - config_hardware_lights.yaml
  - config_hardware_switches.yaml
  - config_hardware_coils.yaml
  - config_hardware_motors.yaml
                          
game:
  balls_per_game: 3
  max_players: 4

player_vars:
  bonus_multiplier:
    value_type: int
    initial_value: 1
  skull_ramp_nb:
    value_type: int
    initial_value: 0
  skillshot:
    value_type: int
    initial_value: 0
  skillshot_count:
    value_type: int
    initial_value: 0
  tmp_int:
    value_type: int
    initial_value: 0
  bip:
    value_type: int
    initial_value: 0

modes:
  - attract
  - base
  - skillshot
  - bumpers
  - selectmission
  - skull
  - skull_wave1
  - skull_wave2
  - skull_wave3
  - skull_wave4
  - csi_lanes
  
