#config_version=6

lights:
  l_skillshot:
    number:

# Bottom lanes
# CSI Lanes
  l_lane_c:
    number:
  l_lane_s:
    number:
  l_lane_i:
    number:

  l_scoop_bonus:
    number:  

  l_right_orbit_bonus:
    number:

# Skull
  l_skull_light_lock:
    number:
  l_skull_lock1:
    number:
  l_skull_lock2:
    number:
    
  # Arrows
  l_left_orbit_arrow:
    number:
  l_centriguge_arrow:
    number:
  l_ramp_arrow:
    number:
  l_microscope_left_arrow:
    number:
  l_microscope_right_arrow:
    number:
  l_right_spinner_arrow:
    number:
